# Generated by Django 5.1.15 on 2026-02-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
