# Generated by Django 5.1.15 on 2026-02-21 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', max_length=100)),
                ('tagline', models.CharField(default='Creative Developer', max_length=200)),
                ('hero_heading', models.CharField(default='Crafting Digital Experiences', max_length=200)),
                ('hero_subheading', models.TextField(default='I transform ideas into elegant, functional, and memorable digital solutions.')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/')),
                ('resume_file', models.FileField(blank=True, upload_to='resume/')),
                ('years_experience', models.PositiveIntegerField(default=5)),
                ('projects_completed', models.PositiveIntegerField(default=50)),
                ('happy_clients', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='CSS icon class or emoji', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
