# Generated by Django 5.1.15 on 2026-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillcategory',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
